language: python
python:
  - "3.5"
script:
    - nose2

sudo: required

before_install:
  # Setup ray from https://s3-us-west-2.amazonaws.com/ray-wheels/
  - pushd ../
  - pip install https://s3-us-west-2.amazonaws.com/ray-wheels/3d224c4edfc4f96d72e8b281fc39ca3573ed8382/ray-0.3.0-cp35-cp35m-manylinux1_x86_64.whl

  # Copy over local rllib changes (testing branch)
  - git clone https://github.com/cathywu/ray.git
  - pushd ray
  - pwd
  - git checkout testing
  - RAY_SITE_DIR=`python -c "import ray; print(ray.__path__[0])"`
  - ls $RAY_SITE_DIR
  - ls $RAY_SITE_DIR/rllib
  - rm -rf $RAY_SITE_DIR/rllib
  - cp -r python/ray/rllib $RAY_SITE_DIR/rllib
  - popd
  - popd

  # Setup SUMO
  - bash scripts/setup_sumo_linux.sh $HOME/build/cathywu
  - export SUMO_HOME="$HOME/build/cathywu/sumo"
  - export PYTHONPATH="$SUMO_HOME/tools:$PYTHONPATH"
  - export PATH="$SUMO_HOME/bin:$PATH"
  - ls ../
